#!/bin/sh
#
# gen_build_info.sh -- creates vr_build_info.c in dp-core/ for dkms
# builds
#
# Copyright (c) 2015, Juniper Networks, Inc.
# All rights reserved
#

build_info_file="$2/dp-core/vr_buildinfo.c"
build_info_header="$2/include/vr_buildinfo.h"


cat <<EOF > $build_info_file
/*
 * Autogenerated file. Do not edit.
 */

char *ContrailBuildInfo = "{\"build-info\": [{\"build-time\": \"`date`\", \"build-hostname\": \"`hostname`\", \"build-git-ver\": \"dkms\", \"build-user\": \"`whoami`\", \"build-version\": \"$1-dkms\"}]}";

EOF

cat <<EOF > $build_info_header
/*
 * Autogenerated file. Do not edit.
 */

#ifndef __VR_BUILDINFO_H__
#define __VR_BUILDINFO_H__

#define VROUTER_VERSIONID "$1"

#endif /* __VR_BUILDINFO_H__ */
EOF

