#
# Copyright (c) 2014 Juniper Networks, Inc. All rights reserved.
#

import platform

Import('VRouterEnv')
env = VRouterEnv.Clone()

if platform.system() == 'Windows':
    env.SConscript('windows/SConscript', exports='VRouterEnv', duplicate=0)

vrouter_suite = []

# Include paths
env.Append(CPPPATH = env['TOP_INCLUDE'])
env.Replace(LIBPATH = env['TOP_LIB'])
env.Append(LIBPATH = ['../host', '../sandesh', '../dp-core'])
env.Replace(LIBS = ['dp_core', 'vrouter', 'dp_sandesh_c', 'vrouter', 'dp_core', 'dp_sandesh_c', 'dp_core', 'sandesh-c', 'cmocka'])

if platform.system() == 'Windows':
    env.Append(LIBS = ['Ws2_32', 'windowsstubs'])
else:
    env.Append(LIBS = ['urcu-bp'])

test_dep_srcs = ['common_test.c']

dp_core_test = VRouterEnv.MakeTestCmd(env, 'dp_core_test', vrouter_suite, test_dep_srcs)

test = env.TestSuite('vrouter-test', vrouter_suite)
env.Alias('vrouter:test', test)
Return('vrouter_suite')
