#
# Copyright (c) 2018 Juniper Networks, Inc. All rights reserved.
#

# This SConscript is used only for userspace tests of vrouter

Import('VRouterEnv')
env = VRouterEnv.Clone()

env.Append(CPPPATH = [env['TOP_INCLUDE'], '../test/windows/include'])

# Treat warnings as errors
env.Append(CPPFLAGS = '/WX')

# Files should be added when needed to this list
sources = [
    'win_packet.c',
    'win_pclone.c',
    'win_pfree.c',
]

env.StaticLibrary('win_packet', source = sources)
