/*
 * windows_ksync.h -- definitions used in KSync handling on Windows
 *
 * Copyright (c) 2017 Juniper Networks, Inc. All rights reserved.
 */
#ifndef __WINDOWS_KSYNC_H__
#define __WINDOWS_KSYNC_H__

#define KSYNC_MAX_BUFFER_SIZE   4096

typedef struct _KSYNC_RESPONSE   KSYNC_RESPONSE;
typedef struct _KSYNC_RESPONSE *PKSYNC_RESPONSE;
struct _KSYNC_RESPONSE {
    PKSYNC_RESPONSE next;
    size_t message_len;
    uint8_t buffer[KSYNC_MAX_BUFFER_SIZE];
};

typedef struct _KSYNC_DEVICE_CONTEXT   KSYNC_DEVICE_CONTEXT;
typedef struct _KSYNC_DEVICE_CONTEXT *PKSYNC_DEVICE_CONTEXT;
struct _KSYNC_DEVICE_CONTEXT {
    // Queue for responses generated by vRotuer
    PKSYNC_RESPONSE responses;

    size_t WrittenBytes;
    size_t WriteBufferSize;
    uint8_t WriteBuffer[KSYNC_MAX_BUFFER_SIZE];
};

#endif /* __WINDOWS_KSYNC_H__ */
