#
# Copyright (c) 2013 Juniper Networks, Inc. All rights reserved.
#

Import('VRouterEnv')
env = VRouterEnv.Clone()

# Include paths

# CFLAGS
env.Append(CCFLAGS = '-g')

env.Replace(LIBPATH = env['TOP_LIB'])
env.Append(LIBPATH = ['../host', '../sandesh', '../dp-core'])
env.Replace(LIBS = ['vrouter', 'dp_core', 'dp_sandesh_c', 'sandesh-c', 'rt', 'dp_core'])

uvrouter_sources = ['uvrouter.c']
uvrouter = env.Program(target = 'uvrouter', source = uvrouter_sources)

# to make sure that all are built when you do 'scons' @ the top level
env.Default(uvrouter)
# Local Variables:
# mode: python
# End:
