#
# Copyright (c) 2018 Juniper Networks, Inc. All rights reserved.
#

Import('VRouterEnv')
env = VRouterEnv.Clone()

env.Append(CPPPATH = [env['TOP_INCLUDE'], 'include'])

# Treat warnings as errors
env.Append(CPPFLAGS = '/WX')

env.Replace(LIBPATH = env['TOP_LIB'])
env.Append(LIBPATH = ['.', '../../windows'])

# vRouter code
env.Replace(LIBS = ['win_packet'])
# 3rd party libs
env.Append(LIBS = 'cmocka')

env.AppendENVPath('Path', Dir('#build/bin'))
test_sources = [
    'test.c', 'fake_win_packet_raw.c', 'test_win_packet_clone.c', 'test_win_pclone.c'
]
test_runner = env.UnitTest('test_runner', test_sources)
kernel_tests = env.TestSuite('kernel-tests', [test_runner])
env.Requires(kernel_tests, '#build/bin/cmocka.dll')
