#!/bin/sh
##
## vRouter/DPDK vif tcpdump
##

## Constants
MON_IF_NAME="mon"
VR_MAX_INTERFACES=$((256 + 4096))
MON_TYPE="monitoring"

## Functions
usage () {
    echo "vRouter/DPDK vif tcmpdump script"
    echo "Usage:"
    echo "      ${0##*/} [-i] <vif> [tcpdump arguments]"
    echo "              - to run tcpdump on a specified vif"
    echo "      ${0##*/} stop <monitoring_if>"
    echo "              - to force stop and clean up the monitoring interface"
    echo "Example:"
    echo "      ${0##*/} -i vif0/1 -nvv"
    exit 1
}

error () {
    echo "${0##*/} error: $1"
    exit 1
}

monitoring_stop () {
    if [ $# -lt 1 ]; then
        usage
    fi
    MONITORING_VIF_ID=${1##vif0/}
    MONITORING_VIF_ID=${MONITORING_VIF_ID##mon}
    echo "Deleting vif ${MONITORING_VIF_ID}..."
    sudo vif --delete ${MONITORING_VIF_ID}
    exit 0
}

## parse the arguments
if [ $# -lt 1 ]; then
    usage
fi

ARG=${1}; shift
case ${ARG} in
    "-i" )
        ARG=${1}
        shift
        ;;
    "stop" )
        monitoring_stop ${1};;
esac
MONITORED_VIF_ID=${ARG##vif0/}

## check if the monitoring interface is free
MON_IF_ID=${MONITORED_VIF_ID}
vif --get ${MON_IF_ID} | grep "vif0/${MON_VIF_ID}"
if [ $? -ne 0 ]; then
        error "Invalid Vif Id"
fi
if ifconfig ${MON_IF_NAME}${MON_IF_ID} >/dev/null 2>&1; then
    echo "monitoring interface ${MON_IF_NAME}${MON_IF_ID} is already in use"
    MON_VIF_ID=`sudo vif --list | grep -w ${MON_IF_NAME}${MON_IF_ID} \
        | cut -d ' ' -f 1 | cut -d '/' -f 2`
    if [ -n "${MON_VIF_ID}" ]; then
        error "Use '${0##*/} stop ${MON_VIF_ID}' command to force stop the monitoring."
    else
        error "Use 'vif --list' and '${0##*/} stop <id>' commands to force stop the monitoring."
    fi
fi

## find free monitoring vif index
MON_VIF_ID=$((${VR_MAX_INTERFACES} - ${MON_IF_ID} - 1))
while true; do
    if ! sudo vif --list 2>/dev/null | grep "^vif0/${MON_VIF_ID}\b" >/dev/null 2>&1; then
        break
    fi
    MON_VIF_ID=$((${MON_VIF_ID} - 1))
done

sudo vif --add ${MON_IF_NAME}${MON_IF_ID} --type ${MON_TYPE} \
    --vif ${MONITORED_VIF_ID} --id ${MON_VIF_ID} >/dev/null

## wait for monitoring interface to appear
WAIT=10
while ! ifconfig ${MON_IF_NAME}${MON_IF_ID} >/dev/null 2>&1; do
    WAIT=$((${WAIT} - 1))
    if [ "${WAIT}" = "0" ]; then
        error "no interface ${MON_IF_NAME}${MON_IF_ID}"
    fi
done

## disable IPv6 on the monitoring interface
sudo sh -c "echo 1 > /proc/sys/net/ipv6/conf/${MON_IF_NAME}${MON_IF_ID}/disable_ipv6"

sudo ifconfig ${MON_IF_NAME}${MON_IF_ID} up

## set signal handler
trap "echo ${0##*/}: deleting vif ${MON_VIF_ID}...; \
    sudo vif --delete ${MON_VIF_ID}; exit 0" \
    HUP INT QUIT ABRT PIPE TERM

## run tcpdump with the rest of arguments
sudo tcpdump -i ${MON_IF_NAME}${MON_IF_ID} $*

trap "exit 1" \
    HUP INT QUIT ABRT PIPE TERM
echo ${0##*/}: deleting vif ${MON_VIF_ID}...
sudo vif --delete ${MON_VIF_ID}
