#
# Copyright (c) 2013 Juniper Networks, Inc. All rights reserved.
#

import platform

Import('VRouterEnv')
env = VRouterEnv.Clone()

if platform.system() == 'Windows':
    env.Append(CPPDEFINES = '__KERNEL__')
    env.Append(CPPPATH = [env['TOP_INCLUDE'], '../test/windows/kernel_impl/include'])

    # Treat warnings as errors
    env.Append(CPPFLAGS = '/WX')

env.Library('dp_core', Glob('*.c'))

if 'install' in COMMAND_LINE_TARGETS:
    env.Append(SRC_INSTALL_TARGET = '/dp-core/')
    env.Install(env['SRC_INSTALL_TARGET'], Glob('*.c'))
    env.Alias('install', env['SRC_INSTALL_TARGET'])

# Local Variables:
# mode: python
# End:
