#
# Copyright (c) 2013 Juniper Networks, Inc. All rights reserved.
#

Import('VRouterEnv')
env = VRouterEnv.Clone()

if 'install' in COMMAND_LINE_TARGETS:
    env.Append(SRC_INSTALL_TARGET = '/include/')
    env.Install(env['SRC_INSTALL_TARGET'], Glob('*.h'))
    env.Alias('install', env['SRC_INSTALL_TARGET'])

# Local Variables:
# mode: python
# End:
