/*
 * ksync_device_context.h
 *
 * Copyright (c) 2019 Juniper Networks, Inc. All rights reserved.
 */
#ifndef __KSYNC_DEVICE_CONTEXT_H__
#define __KSYNC_DEVICE_CONTEXT_H__

#include <windows_types.h>
#include "ksync_response.h"

typedef struct _KSYNC_DEVICE_CONTEXT KSYNC_DEVICE_CONTEXT;
typedef struct _KSYNC_DEVICE_CONTEXT *PKSYNC_DEVICE_CONTEXT;
struct _KSYNC_DEVICE_CONTEXT {
    // Queue for responses generated by vRotuer
    PKSYNC_RESPONSE responses;

    size_t WrittenBytes;
    size_t WriteBufferSize;
    uint8_t WriteBuffer[KSYNC_MAX_BUFFER_SIZE];
};

PKSYNC_DEVICE_CONTEXT KsyncAllocContext();

VOID KsyncContextResetWriteBuffer(PKSYNC_DEVICE_CONTEXT ctx);

VOID KsyncCopyUserBufferToContext(PKSYNC_DEVICE_CONTEXT ctx,
                                  ULONG bytesNeeded,
                                  PCHAR *userBuffer,
                                  ULONG *userBufferSize,
                                  ULONG *writtenBytes);

VOID KsyncAppendResponse(PKSYNC_DEVICE_CONTEXT ctx,
                         PKSYNC_RESPONSE resp);

VOID KsyncPrependResponse(PKSYNC_DEVICE_CONTEXT ctx,
                          PKSYNC_RESPONSE resp);

PKSYNC_RESPONSE KsyncPopResponse(PKSYNC_DEVICE_CONTEXT ctx);

VOID KsyncDeleteContext(PKSYNC_DEVICE_CONTEXT ctx);

#endif // __KSYNC_DEVICE_CONTEXT_H__
