#
# Copyright (c) 2013 Juniper Networks, Inc. All rights reserved.
#

Import('VRouterEnv')
env = VRouterEnv.Clone()

DpSandeshFiles = env.SandeshGenC('vr.sandesh')
DpSandeshFilesSrc = env.ExtractC(DpSandeshFiles)
libdp_sandesh = env.Library('dp_sandesh_c', DpSandeshFilesSrc)

sandesh_sources = [
                    '#tools/sandesh/library/c/sandesh.c',
                    '#tools/sandesh/library/c/sandesh.h',
                    '#tools/sandesh/library/c/thrift.h',
                  ]

sandesh_protocol_sources = [
                    '#tools/sandesh/library/c/protocol/thrift_binary_protocol.c',
                    '#tools/sandesh/library/c/protocol/thrift_binary_protocol.h',
                    '#tools/sandesh/library/c/protocol/thrift_protocol.c',
                    '#tools/sandesh/library/c/protocol/thrift_protocol.h',
                  ]

sandesh_transport_sources = [
                    '#tools/sandesh/library/c/transport/thrift_fake_transport.h',
                    '#tools/sandesh/library/c/transport/thrift_fake_transport.c',
                    '#tools/sandesh/library/c/transport/thrift_memory_buffer.c',
                    '#tools/sandesh/library/c/transport/thrift_memory_buffer.h',
                    '#tools/sandesh/library/c/transport/thrift_transport.h',
                 ]

sandesh_generateds = [
                      'gen-c/vr_types.c',
                      'gen-c/vr_types.h'
                     ]

if 'install' in COMMAND_LINE_TARGETS:
    env.Append(SRC_INSTALL_TARGET = '/sandesh/')
    env.Install(env['SRC_INSTALL_TARGET'] + 'gen-c/', sandesh_generateds)
    env.Install(env['SRC_INSTALL_TARGET'] + 'library/c/', sandesh_sources)
    env.Install(env['SRC_INSTALL_TARGET'] + 'library/c/protocol/', sandesh_protocol_sources)
    env.Install(env['SRC_INSTALL_TARGET'] + 'library/c/transport/', sandesh_transport_sources)
    env.Alias('install', env['SRC_INSTALL_TARGET'])

# Local Variables:
# mode: python
# End:
